export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED = 'AUTH_SIGNUP_FAILED';

export const AUTH_SIGNIN_START = 'AUTH_SIGNIN_START';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILED = 'AUTH_SIGNIN_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FIND_USER_BY_ID_START = 'FIND_USER_BY_ID_START';
export const FIND_USER_BY_ID_SUCCESS = 'FIND_USER_BY_ID_SUCCESS';
export const FIND_USER_BY_ID_FAILED = 'FIND_USER_BY_ID_FAILED';

export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FALIED = 'FETCH_CATEGORY_FALIED';

export const FETCH_POSTS_BY_USER_ID_START = 'FETCH_POSTS_BY_USER_ID_START';
export const FETCH_POSTS_BY_USER_ID_SUCCESS = 'FETCH_POSTS_BY_USER_ID_SUCCESS';
export const FETCH_POSTS_BY_USER_ID_FAILED = 'FETCH_POSTS_BY_USER_ID_FAILED';
